run-dist:
	@./build/install/app/bin/app

run:
	@./gradlew run

report:
    @./gradlew jacocoTestReport

build:
	@./gradlew clean build

test:
	@./gradlew test

lint:
	@./gradlew checkstyleMain checkstyleTest

.PHONY: build
